const getters = {
  sidebar: (state) => state.app.sidebar,
  language: (state) => state.app.language,
  isrtl: (state) => state.app.isrtl,
  size: (state) => state.app.size,
  device: (state) => state.app.device,
  visitedViews: (state) => state.tagsView.visitedViews,
  cachedViews: (state) => state.tagsView.cachedViews,
  token: (state) => state.user.token,
  avatar: (state) => state.user.avatar,
  name: (state) => state.user.name,
  username: (state) => state.user.username,
  userid: (state) => state.user.id,
  introduction: (state) => state.user.introduction,
  status: (state) => state.user.status,
  role: (state) => state.user.role,
  setting: (state) => state.user.setting,
  permission_routers: (state) => state.permission.routers,
  addRouters: (state) => state.permission.addRouters,
  errorLogs: (state) => state.errorLog.logs,
  privileges: (state) => state.user.privileges,
};
export default getters;
